<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Sécu</title>
    </head>
    <body>
        <form action="defense.php" method="post">
            <fieldset>
                <label for="text">Text</label>
                <textarea name="text" rows="5" cols="33">
                </textarea>
            </fieldset>
            <fieldset>
                <input type="submit" name="submit"/>
            </fieldset>
        </form>
        <?= var_dump($_POST); ?>
    </body>
</html>